# shell-runner configuration

# prepare gitlab-ci
before_script:
- php -d memory_limit=-1 composer.phar install

# define types/stages
types:
- test

# testing with php 5.x jobs
test-php55_job:
  type: test
  image: php:5.5
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./test/phpunit.xml --coverage-text
  allow_failure: false

test-php56_job:
  type: test
  image: php:5.6
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./test/phpunit.xml --coverage-text
  allow_failure: false

test-php70_job:
  type: test
  image: php:7.0
  script:
  - php -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./test/phpunit.xml --coverage-text
  allow_failure: false


