# shell-runner configuration

# prepare gitlab-ci
before_script:
- curl -sS https://getcomposer.org/installer | php
- php composer.phar --version

# define types/stages
types:
- test

test-php56_job:
  type: test
  image: php:5.6
  script:
  - php56 -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false

test-php70_job:
  type: test
  image: php:7.0
  script:
  - php70 -d memory_limit=-1 vendor/bin/phpunit --colors --debug --configuration ./tests/phpunit.xml --coverage-text
  allow_failure: false


