checks:
    php: true
filter:
    paths:
        - src/*
    excluded_paths:
        - test/*
        - vendor/*
        - public/*
        - puphpet/*
coding_style:
    php: {  }
build:
    environment:
        php: '7.0'
        timezone: 'Europe/Berlin'
    tests:
        before:
            - php -m
            - php -d memory_limit=-1 composer.phar install
        override:
            -
                command: './vendor/bin/phpunit -c ./tests --coverage-clover=/home/scrutinizer/build/slmlocale.clover'
                coverage:
                    file: '/home/scrutinizer/build/slmlocale.clover'
                    format: 'php-clover'

